FROM centos:centos7
MAINTAINER 275862485@qq.com
RUN yum -y install wget git; yum clean all
#RUN wget https://download.calibre-ebook.com/4.6.0/calibre-4.6.0-x86_64.txz > /dev/null 2>&1
#RUN git clone https://github.com/istio/istio.io.git > /dev/null 2>&1
RUN git clone https://github.com/torvalds/linux.git > /dev/null 2>&1
