FROM centos:centos7
MAINTAINER 275862485@qq.com
RUN yum -y update; yum clean all
RUN yum -y install wget; yum clean all
RUN wget https://github.com/istio/istio/releases/download/1.2.0/istio-1.2.0-linux.tar.gz /

