FROM centos:centos7
MAINTAINER 275862485@qq.com
RUN yum -y update; yum clean all
RUN yum -y install wget; yum clean all
RUN wget https://github.com/kubernetes/kubernetes/archive/v1.15.2.zip > /dev/null 2>&1

